export const ChatEventEnum = Object.freeze({
  // ? once user is ready to go
  CONNECTED_EVENT: "connected",
  // ? when user gets disconnected
  DISCONNECT_EVENT: "disconnect",
  // ? when user joins a socket room
  JOIN_CHAT_EVENT: "joinChat",
  // ? when participant gets removed from group, chat gets deleted or leaves a group
  LEAVE_CHAT_EVENT: "leaveChat",
  // ? when admin updates a group name
  UPDATE_GROUP_NAME_EVENT: "updateGroupName",
  // ? when new message is received
  MESSAGE_RECEIVED_EVENT: "messageReceived",
  // ? when there is new one on one chat, new group chat or user gets added in the group
  NEW_CHAT_EVENT: "newChat",
  // ? when there is an error in socket
  SOCKET_ERROR_EVENT: "socketError",
  // ? when participant stops typing
  STOP_TYPING_EVENT: "stopTyping",
  // ? when participant starts typing
  TYPING_EVENT: "typing",
});

export const currencyMap = {
  "United Arab Emirates": "aed",
  "Afghanistan": "afn",
  "Albania": "all",
  "Armenia": "amd",
  "Netherlands Antilles": "ang",
  "Angola": "aoa",
  "Argentina": "ars",
  "Australia": "aud",
  "Aruba": "awg",
  "Azerbaijan": "azn",
  "Bosnia and Herzegovina": "bam",
  "Barbados": "bbd",
  "Bangladesh": "bdt",
  "Bulgaria": "bgn",
  "Burundi": "bif",
  "Bermuda": "bmd",
  "Brunei": "bnd",
  "Bolivia": "bob",
  "Brazil": "brl",
  "Bahamas": "bsd",
  "Botswana": "bwp",
  "Belarus": "byn",
  "Belize": "bzd",
  "Canada": "cad",
  "Democratic Republic of the Congo": "cdf",
  "Switzerland": "chf",
  "Chile": "clp",
  "China": "cny",
  "Colombia": "cop",
  "Costa Rica": "crc",
  "Cape Verde": "cve",
  "Czech Republic": "czk",
  "Djibouti": "djf",
  "Denmark": "dkk",
  "Dominican Republic": "dop",
  "Algeria": "dzd",
  "Egypt": "egp",
  "Ethiopia": "etb",
  "Eurozone": "eur",
  "Fiji": "fjd",
  "Falkland Islands": "fkp",
  "United Kingdom": "gbp",
  "Georgia": "gel",
  "Gibraltar": "gip",
  "Gambia": "gmd",
  "Guinea": "gnf",
  "Guatemala": "gtq",
  "Guyana": "gyd",
  "Hong Kong": "hkd",
  "Honduras": "hnl",
  "Croatia": "hrk",
  "Haiti": "htg",
  "Hungary": "huf",
  "Indonesia": "idr",
  "Israel": "ils",
  "India": "inr",
  "Iceland": "isk",
  "Jamaica": "jmd",
  "Japan": "jpy",
  "Kenya": "kes",
  "Kyrgyzstan": "kgs",
  "Cambodia": "khr",
  "Comoros": "kmf",
  "South Korea": "krw",
  "Cayman Islands": "kyd",
  "Kazakhstan": "kzt",
  "Laos": "lak",
  "Lebanon": "lbp",
  "Sri Lanka": "lkr",
  "Liberia": "lrd",
  "Lesotho": "lsl",
  "Morocco": "mad",
  "Moldova": "mdl",
  "Madagascar": "mga",
  "North Macedonia": "mkd",
  "Myanmar": "mmk",
  "Mongolia": "mnt",
  "Macau": "mop",
  "Mauritania": "mro",
  "Mauritius": "mur",
  "Maldives": "mvr",
  "Malawi": "mwk",
  "Mexico": "mxn",
  "Malaysia": "myr",
  "Mozambique": "mzn",
  "Namibia": "nad",
  "Nigeria": "ngn",
  "Nicaragua": "nio",
  "Norway": "nok",
  "Nepal": "npr",
  "New Zealand": "nzd",
  "Panama": "pab",
  "Peru": "pen",
  "Papua New Guinea": "pgk",
  "Philippines": "php",
  "Pakistan": "pkr",
  "Poland": "pln",
  "Paraguay": "pyg",
  "Qatar": "qar",
  "Romania": "ron",
  "Serbia": "rsd",
  "Russia": "rub",
  "Rwanda": "rwf",
  "Saudi Arabia": "sar",
  "Solomon Islands": "sbd",
  "Seychelles": "scr",
  "Sweden": "sek",
  "Singapore": "sgd",
  "Saint Helena": "shp",
  "Sierra Leone": "sll",
  "Somalia": "sos",
  "Suriname": "srd",
  "São Tomé and Príncipe": "std",
  "Eswatini": "szl",
  "Thailand": "thb",
  "Tajikistan": "tjs",
  "Tonga": "top",
  "Turkey": "try",
  "Trinidad and Tobago": "ttd",
  "Taiwan": "twd",
  "Tanzania": "tzs",
  "Ukraine": "uah",
  "Uganda": "ugx",
  "United States": "usd",
  "Uruguay": "uyu",
  "Uzbekistan": "uzs",
  "Vietnam": "vnd",
  "Vanuatu": "vuv",
  "Samoa": "wst",
  "Central African States": "xaf",
  "East Caribbean": "xcd",
  "West African States": "xof",
  "French Territories": "xpf",
  "Yemen": "yer",
  "South Africa": "zar",
  "Zambia": "zmw"
};
